DROP TABLE users;
DROP TABLE languages;
DROP TABLE user_languages;

CREATE TABLE users (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username text NOT NULL
);

CREATE TABLE languages (
    id integer GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
    language text not NULL
);

CREATE TABLE user_languages (
  user_id integer NOT NULL,
  language_id integer NOT NULL
);
-- Composite key;
ALTER TABLE user_languages ADD CONSTRAINT user_language_pkey PRIMARY KEY (user_id, language_id);
ALTER TABLE user_languages ADD CONSTRAINT user_language_users_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_languages ADD CONSTRAINT user_language_languages_fkey FOREIGN KEY (language_id) REFERENCES languages(id);


SELECT * FROM users;