// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Languages     string
	UserLanguages string
	Users         string
}{
	Languages:     "languages",
	UserLanguages: "user_languages",
	Users:         "users",
}
